inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Rakefile'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
  TargetRubyVersion: 2.3